name: weather_forecast_app
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  bloc: ^8.0.2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  client_api:
    path: client_api
  dio: ^4.0.0
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.0.0+2
  flutter_staggered_grid_view: ^0.6.1
  geolocator: ^8.2.1
  get_it: ^7.1.3
  google_fonts: ^2.3.2
  injectable: ^1.5.3
  json_annotation: ^4.3.0
  pretty_dio_logger: ^1.1.1
  shared_preferences: ^2.0.8
  
dev_dependencies:
  build_runner: ^2.1.2
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  injectable_generator: ^1.5.3
  json_serializable: ^6.1.4




flutter:

  uses-material-design: true
 
  # assets:
  #   - assets/images/
 
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

